import '@/styles/globals.css';
import { type Metadata } from 'next';
import { geistSans } from '@/lib/fonts';
import { cn } from '@/utils/cn';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(geistSans.variable, 'font-geist antialiased')}>
        {children}
      </body>
    </html>
  );
}
